Added new simplifier - ExponentiationPolynomial
artfly/java-seminar-2022 pull request #1
Opened 2022-03-29 02:13 UTC by plugatarev

2022-04-02 10:18 UTC, artfly commented
Can you please rebase your branch to master? Here's an instruction: https://dev.to/matks/what-it-means-to-rebase-a-pull-request-submitted-on-github-5717
I believe I cannot do it by myself since it requires force push to your fork

2022-04-02 16:45 UTC, plugatarev commented
Rebase branch to master

2022-04-24 06:55 UTC, artfly requested changes

2022-04-24 06:55 UTC, artfly commented on arith-simplifier/src/main/java/com/github/artfly/simplifier/simplifier/ExponentiationPolynomial.java
> +    int getBinomialCoefficient(int k, int n){
can simplify to ((n - k + 1) * (n - k + 2) ... * n) / factorial(n - k)

2022-04-24 06:55 UTC, artfly commented on arith-simplifier/src/main/java/com/github/artfly/simplifier/simplifier/ExponentiationPolynomial.java
> +                if (b.lhs() instanceof Expr.Binary bin){
please rename to lhsBin

2022-04-26 15:38 UTC, plugatarev commented on arith-simplifier/src/main/java/com/github/artfly/simplifier/simplifier/ExponentiationPolynomial.java
> +    int getBinomialCoefficient(int k, int n){
made new method truncatedFactorial by which I count binomial coefficient

2022-04-26 15:39 UTC, plugatarev commented
corrected remarks

2022-04-26 17:45 UTC, merged

2022-04-26 17:45 UTC, artfly commented
merged, thanks!